name: Simple test

on:
  # define reusable section
  workflow_call:
    inputs:
      test-a:
        description: "Define test a"
        # required: true
        type: string
        default: 'false'
      test-b:
        description: "Define test b"
        # required: true
        type: string
        default: 'true'
      param-1:
        description: "Define param 1"
        type: string
        default: ''
      param-2:
        description: "Define param 2"
        type: string
        default: 'value'

env:
  TERRAFORM_VERSION: 1.4.3

jobs:
  prepare:
    name: prepare
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      #   with:
      #     ref: main
      #     fetch-depth: 1
      - name: Test shell
        run: |

          echo build \
            ${{ inputs.test-a == 'true' && '--test-a' || '' }} \
            ${{ inputs.test-b == 'true' && '--test-b' || '' }} \
            ${{ inputs.param-1 != '' && "--param-1=${{ inputs.param-1 }}" || '' }} \
            ${{ inputs.param-2 != '' && "--param-2=${{ inputs.param-2 }}" || '' }} \
            params

          # if [ -d "${{ inputs.project_path }}" ]; then
          #     echo "Directory ${{ inputs.project_path }} exists."
          #     echo "all_changed_files=[\"${{ inputs.project_path }}\"]" >> "$GITHUB_OUTPUT"
          #     echo "any_changed=true" >> "$GITHUB_OUTPUT"
          # else
          #     echo "Warnining: Directory ${{ inputs.project_path }} does not exists."
          #     echo "all_changed_files=[]" >> "$GITHUB_OUTPUT"
          #     echo "any_changed=false" >> "$GITHUB_OUTPUT"
          # fi
