name: "Terraform"

on:
  # define reusable section
  workflow_call:
    inputs:
      project_id:
        required: true
        type: string
    secrets:
      GOOGLE_CREDENTIALS:
        required: true

env:
  TERRAFORM_VERSION: 1.4.3

jobs:
  prepare:
    name: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed environments(s)
        id: changes-as-json
        uses: dawidmalina/actions-hub/wrapped-changed-directories@main
        with:
          dir_names_max_depth: "3"
          files: |
            **/*.tf
    outputs:
      all_changed_files: ${{ steps.changes-as-json.outputs.all_changed_files }}
      any_changed: ${{ steps.changes-as-json.outputs.any_changed }}

  terraform:
    name: plan-apply
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: needs.prepare.outputs.any_changed == 'true'
    needs: prepare
    strategy:
      matrix:
        dir: ${{ fromJson(needs.prepare.outputs.all_changed_files) }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    # Set the working directory to main for the config files
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.dir }}

    steps:
      # Make sure GitHUb Actions runner is monitored (secured)
      - name: Harden Runner
        uses: step-security/harden-runner@v2.1.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # TODO switch to this approach
      # - id: 'auth'
      #   name: 'Authenticate to Google Cloud'
      #   uses: google-github-actions/auth@v0.7.0
      #   with:
      #     create_credentials_file: 'true'
      #     workload_identity_provider: <write what you got from terraform output>
      #     service_account: <write what you got from terrafrom output>

      # - name: Configure GCP credentials
      #   uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      #   with:
      #     service_account_key: ${{ secrets.GCP_SA_KEY }}
      #     project_id: <GCP_PROJECT_ID>
      #     export_default_credentials: true

      # Install the preferred version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_wrapper: false
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Fmt
        if: github.event.pull_request.merged != true && github.event.pull_request.state != 'closed' || failure()
        id: fmt
        run: |
          terraform fmt -check

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        id: init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VAR_project_id: ${{ inputs.project_id }}
        run: |
          terraform init

      - name: Terraform Security
        if: github.event.pull_request.merged != true && github.event.pull_request.state != 'closed' || failure()
        id: security
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true

      # - name: Checkov security scan
      #   if: github.event.pull_request.merged != true && github.event.pull_request.state != 'closed'
      #   id: security
      #   uses: bridgecrewio/checkov-action@master
      #   with:
      #     version: latest
      #     directory: ./terraform
      #     fail_on_violations: true

      - name: Terraform Validate
        if: github.event.pull_request.merged != true && github.event.pull_request.state != 'closed' || failure()
        id: validate
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VAR_project_id: ${{ inputs.project_id }}
        run: |
          terraform validate -no-color

      # Run a terraform plan for pull requests only
      - name: Terraform Plan
        if: github.event.pull_request.merged != true && github.event.pull_request.state != 'closed' || failure()
        id: plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VAR_project_id: ${{ inputs.project_id }}
        run: |
          terraform plan -no-color -out tfplan

          echo "cloud=$( echo ${{ matrix.dir }} |cut -d'/' -f1 )" >> "$GITHUB_OUTPUT"
          echo "environment=$( echo ${{ matrix.dir }} |cut -d'/' -f2 )" >> "$GITHUB_OUTPUT"
          echo "region=$( echo ${{ matrix.dir }} |cut -d'/' -f3 )" >> "$GITHUB_OUTPUT"

          echo "summary<<EOF" >> $GITHUB_OUTPUT
          terraform show -no-color tfplan |grep -E 'Plan:|No changes' |sed '1{/^$/d}' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "tf_plan<<EOF" >> $GITHUB_OUTPUT
          terraform show -no-color tfplan |sed '1{/^$/d}' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # Save plan to artifacts
      - name: Save Plan
        if: github.event.pull_request.merged != true && github.event.pull_request.state != 'closed' || failure()
        id: save-plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: ${{ matrix.dir }}/tfplan
          # if-no-files-found: ignore

      # Add a comment to pull requests with plan results
      - name: Add Plan Comment
        if: github.event.pull_request.merged != true && github.event.pull_request.state != 'closed' || failure()
        id: plan-comment
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          check_for_duplicate_msg: false
          msg: |
            ### Terraform Plan Result

            :ship: Terraform changes contained in this pull request result in the following changes in the **`${{ steps.plan.outputs.environment }}`** environment (region **`${{ steps.plan.outputs.region }}`**):

            ```
            ${{ steps.plan.outputs.summary }}
            ```

            ### Quality Standard Report:

            | Quality Check  | Status |
            | ------------- | ------------- |
            | Terraform Format and Style  | `${{ steps.fmt.outcome }}` |
            | Terraform Initialization | `${{ steps.init.outcome }}` |
            | Terraform Validation | `${{ steps.validate.outcome }}` |
            | Terraform Security | `${{ steps.security.outcome }}` |
            | Terraform Plan | `${{ steps.plan.outcome }}` |

            <details><summary>Show Plan (click)</summary>

            ```terraform
            ${{ steps.plan.outputs.tf_plan }}
            ```
            </details>

            *Pusher: @${{ github.actor }}, Working Directory: `${{ matrix.dir }}`, Cloud Provider: `${{ steps.plan.outputs.cloud }}`*

      # Download saved plan from artifacts
      - name: Download Terraform Plan
        if: github.event.pull_request.merged == true # && github.event.review.state == 'approved'
        id: download-plan
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr: ${{ github.event.pull_request.number }}
          name: tfplan
          path: ${{ matrix.dir }}

      # On push to main, build or change infrastructure according to Terraform configuration files
      - name: Terraform Apply
        if: github.event.pull_request.merged == true # && github.event.review.state == 'approved'
        id: apply
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VAR_project_id: ${{ inputs.project_id }}
        run: |
          terraform apply -auto-approve -input=false -no-color tfplan

      - name: Add Apply Comment
        if: github.event.pull_request.merged == true # && github.event.review.state == 'approved'
        id: apply-comment
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          check_for_duplicate_msg: false
          msg: |
            ### Terraform Apply Result

            :rocket: Terraform changes has been applied!!!

            <details><summary>Show Apply Output (click)</summary>

            ```terraform
            ${{ steps.apply.outputs.stdout }}
            ```
            </details>

            *Pusher: @${{ github.actor }}, Working Directory: `${{ matrix.dir }}`*
