name: Wrapped Changed Directories
description: Get all changed directories.
author: dawidmalina

inputs:
  files:
    description: "File and directory patterns to detect changes using only these list of file(s) (Defaults to the entire repo) **NOTE:** Multiline file/directory patterns should not include quotes."
    required: false
    default: ""
  files_ignore:
    description: "Ignore changes to these file(s) **NOTE:** Multiline file/directory patterns should not include quotes."
    required: false
    default: ""
  dir_names_max_depth:
    description: "Maximum depth of directories to output. e.g `test/test1/test2` with max depth of `2` returns `test/test1`."
    required: false
    default: "2"
  base_sha:
    description: "Specify a different base commit SHA used for comparing changes"
    required: false

outputs:
  all_modified_files:
    description: "Returns all changed files i.e. *a combination of all added, copied, modified and renamed files (ACMR)*"
    value: ${{ steps.set-values.outputs.all_modified_files }}
  any_modified:
    description: "Returns `true` when any of the filenames provided using the `files` input has changed. If no `files` have been specified,an empty string `''` is returned. i.e. *using a combination of all added, copied, modified and renamed files (ACMR)*."
    value: ${{ steps.set-values.outputs.any_modified }}

runs:
  using: "composite"
  steps:
    - uses: tj-actions/changed-files@v37
      id: changed-directories-as-json
      with:
        json: "true"
        dir_names: "true"
        dir_names_max_depth: ${{ inputs.dir_names_max_depth }}
        dir_names_exclude_current_dir: "true"
        files: ${{ inputs.files }}
        files_ignore: ${{ inputs.files_ignore }}
        base_sha: ${{ inputs.base_sha }}

    - name: List all changed dir(s)
      id: set-values
      shell: bash
      run: |
        # debug
        echo all_modified_files=${{ steps.changed-directories-as-json.outputs.all_modified_files }}
        echo any_modified=${{ steps.changed-directories-as-json.outputs.any_modified }}

        echo all_modified_files=${{ steps.changed-directories-as-json.outputs.all_modified_files }} >> $GITHUB_OUTPUT
        echo any_modified=${{ steps.changed-directories-as-json.outputs.any_modified }} >> $GITHUB_OUTPUT

branding:
  icon: file-text
  color: white
