name: Wrapped Changed Directories
description: Get all changed directories.
author: dawidmalina

inputs:
  files_ignore:
    description: "Ignore changes to these file(s) **NOTE:** Multiline file/directory patterns should not include quotes."
    required: false
    default: ""
  dir_names_max_depth:
    description: "Maximum depth of directories to output. e.g `test/test1/test2` with max depth of `2` returns `test/test1`."
    required: false
    default: "2"

outputs:
  all_changed_files:
    description: "Returns all changed files i.e. *a combination of all added, copied, modified and renamed files (ACMR)*"
    value: ${{ steps.set-values.outputs.all_changed_files }}
  any_changed:
    description: "Returns `true` when any of the filenames provided using the `files` input has changed. If no `files` have been specified,an empty string `''` is returned. i.e. *using a combination of all added, copied, modified and renamed files (ACMR)*."
    value: ${{ steps.set-values.outputs.any_changed }}

runs:
  using: "composite"
  steps:
    - uses: tj-actions/changed-files@v35
      id: changed-directories-as-json
      with:
        json: "true"
        dir_names_max_depth: ${{ inputs.dir_names_max_depth }}
        dir_names_exclude_root: "true"
        files_ignore: ${{ inputs.files_ignore }}
    - name: List all changed dir(s)
      id: set-values
      shell: bash
      run: |
        # debug
        echo all_changed_files=${{ steps.changed-directories-as-json.outputs.all_changed_files }}
        echo any_changed=${{ steps.changed-directories-as-json.outputs.any_changed }}
        
        echo other_changed_files=${{ steps.changed-directories-as-json.outputs.other_changed_files }}
        
        echo all_changed_files=${{ steps.changed-directories-as-json.outputs.all_changed_files }} >> $GITHUB_OUTPUT
        echo any_changed=${{ steps.changed-directories-as-json.outputs.any_changed }} >> $GITHUB_OUTPUT

branding:
  icon: file-text
  color: white
